### PR TITLE
Use rect instead of pixel to improve performance

### PR DESCRIPTION
**Pull request by jackpot51**

### CODE REVIEW

**Comment by jackpot51** [comment]
### Before

```
FPS: 1433.6119
FPS: 10937.631
FPS: 2280.0518
FPS: 562.0173
FPS: 4817.6333
FPS: 874.85815
```

### After

```
FPS: 10035.85
FPS: 15122.698
FPS: 12042.89
FPS: 8444.552
FPS: 11977.121
FPS: 9008.146
FPS: 10167.99
FPS: 14616.35
FPS: 13452.519
```

**Comment by pythoneer** [comment]
wow, why is that?

EDIT: ahh sry, did not read the PR carefully

mhh, this only works if the triangle is fully in one color. apparently i am about to change that to have textured triangles ... so this trick does not work anymore :(

**Comment by jackpot51** [comment]
Still, you can be more efficient than calling .pixel

**Comment by pythoneer** [comment]
You're right for this edge case, but i am about to change that to have something like a pixel and vertex shader (don't know how slow this gets) and for this i need to manipulate every pixel. but i agree, maybe i could get and work directly on the framebuffer – but i hadn't  look into that until now

**Comment by jackpot51** [comment]
Work with the framebuffer using window.data_mut(), it will be much faster than .pixel

**Comment by pythoneer** [comment]
great, i hadn't looked into orbclient very briefly – i'll try to use it in the next "release" but thx for the hint. Btw: did you measured the FPS on real hardware/VM/Linux? I tried to get redox running on an old notebook, without much success, to see the real performance of pixelcannon cuz in qemu its like 50 fps.

**Comment by jackpot51** [comment]
I get 350 in Redox, those measurements are from Linux

**Comment by jackpot51** [comment]
You need to update your Redox git, submodules too

**Comment by pythoneer** [comment]
i tried the iso, though. don't know how to install it from scratch (but hadn't tried it neither)

**Comment by jackpot51** [comment]
It should be up to date now

**Pull request merged**
