### PR TITLE
Multiple triangle array, show entire image using two triangles

### PR DESCRIPTION
**Pull request by jackpot51**

### CODE REVIEW

**Comment by pythoneer** [comment]
sure, i let this there until my obj parser is ready to load arbitrary uv mapped (blender) models

**Comment by jackpot51** [comment]
Thanks

**Comment by jackpot51** [comment]
324 FPS on redox - nice!

**Comment by pythoneer** [comment]
I have to thank you :+1:  lets see where we go with more triangles ... but i think the limit is the resolution and how big things are drawn on the screen. blue areas are pretty untouched.

**Comment by jackpot51** [comment]
Updated redox and added the makefile stuff required: https://github.com/redox-os/redox/commit/1b318b085749e47f6faf8685a5b55344bd762ad2

**Comment by jackpot51** [comment]
I would like a cube, I would just need to add 10 more triangles

**Comment by pythoneer** [comment]
nice, orbimage just gave me new motivation ... feel free to add them from your fork i'll merge it

**Comment by jackpot51** [comment]
Sure. I will need to add basic z-ordering too

**Comment by pythoneer** [comment]
sure i guess adding 

```
if min_vert.calc_double_area(&max_vert, &mid_vert) >= 0 {
    return;
}
```

at the beginning of draw_triangle .. should do the trick

(not tested)

**Comment by pythoneer** [comment]
actually its not z-ordering its just backface culling but should be enough for convex shapes like a cube

**Comment by pythoneer** [comment]
i need to implement proper z-ordering anyway with my obj loader

**Comment by jackpot51** [comment]
I will leave it up to you then, I am not as good with maths

**Comment by pythoneer** [comment]
deal.

**Pull request merged**
